name: EconomyEdem
version: ${project.version}
main: com.fozevi.economyedem.EconomyEdem
api-version: 1.16
softdepend: [HolographicDisplays]
authors: [ Fozevi ]
commands:
  ecreate:
    usage: "похуй"
    description: "x2 похуй"
  transfer:
    usage: "похуй2"
    description: "x2 похуй2"
  balance:
    usage: "похуй3"
    description: "x2 похуй3"
  machine:
    usage: "похуй4"
    description: "x2 похуй4"
  convert:
    usage: "похуй5"
    description: "x2 похуй5"
  trade:
    usage: "похуй6"
    description: "x2 похуй6"
  eholo:
    usage: "похуй7"
    description: "x2 похуй7"
  panel:
    usage: "похуй8"
    description: "x2 похуй8"
  einfo:
    usage: "похуй9"
    description: "x2 похуй9"